project:
  type: website
  output-dir: _site

website:
  title: "Blog"
  search: false
  navbar:
    logo-href: /
  comments:
    giscus:
      repo: georgwiese/georgwiese.github.io
      repo-id: R_kgDOTeNUCQ
      category: Announcements
      category-id: DIC_kwDOTeNUCc4DBltP
      mapping: pathname
      reactions-enabled: true
      loading: lazy

format:
  html:
    theme:
      light: [default, theme-light.scss]
      dark: [default, theme-dark.scss]
    css: styles.css
